{
 "title": "MetricsData",
 "description": "Metrics Data of Spring Boot REST API end points",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response Time",
   "type": "gauge",
   "description": "Average response time of the REST API requests.",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "getAllUsers_time_seconds_sum", "legendFormat": "__auto" },
    { "expr": "getUserById_time_seconds_sum", "legendFormat": "__auto" },
    {
     "expr": "addUserDetails_time_seconds_sum",
     "legendFormat": "__auto"
    },
    {
     "expr": "updateUserDetails_time_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate ",
   "type": "stat",
   "description": "Number of requests , every time when the request called , the counter will increased",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_v1_user_adduser_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "api_v1_user_allusers_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "api_v1_user_updateuser_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "api_v1_user_user_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "Percentage of requests that resulted in errors.",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_v1_user_addUserErrors_total",
     "legendFormat": "__auto"
    },
    { "expr": "api_v1_user_getAllErrors_total", "legendFormat": "__auto" },
    {
     "expr": "api_v1_user_updateUserErrors_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "api_v1_user_getUserByIdErrors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jpa Repository Average Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}